%YAML:1.0
features:
  - {x:0.0,   y:0.0,  z:-1.2,  yaw:0.0}
  - {x:0.6,   y:0.3,  z:-1.2,  yaw:0.0}
  - {x:1.0,   y:0.7,  z:-1.2,  yaw:0.0}
  - {x:0.3,   y:1.0,  z:-1.2,  yaw:0.0}
  - {x:-0.3,   y:1.0,  z:-1.2,  yaw:0.0}
  - {x:-1.0,   y:0.7,  z:-1.2,  yaw:0.0}  
  - {x:-0.6,   y:0.3,  z:-1.2,  yaw:0.0}
  - {x:0.0,   y:0.0,  z:-1.2,  yaw:0.0}
  - {x:0.6,   y:-0.3,  z:-1.2,  yaw:0.0}
  - {x:1.0,   y:-0.7,  z:-1.2,  yaw:0.0}
  - {x:0.3,   y:-1.0,  z:-1.2,  yaw:0.0}  
  - {x:-0.3,   y:-1.0,  z:-1.2,  yaw:0.0}
  - {x:-1.0,   y:-0.7,  z:-1.2,  yaw:0.0}
  - {x:-0.6,   y:-0.3,  z:-1.2,  yaw:0.0}
  - {x:0.0,   y:0.0,  z:-1.2,  yaw:0.0}
  - {x:0.0,   y:0.0,  z:-1.2,  yaw:0.0}  