%YAML:1.0
features:
  - {x:1.0,   y:2.0,  z:-1.2,  yaw:0.0}
  - {x:2.0,   y:2.0,  z:-1.2,  yaw:0.0}
  - {x:2.0,   y:1.0,  z:-1.2,  yaw:0.0}
  - {x:1.0,   y:1.0,  z:-1.2,  yaw:0.0}
  - {x:1.0,   y:2.0,  z:-1.2,  yaw:0.0}