%YAML:1.0
features:
  - {x:1.5,   y:1.5,  z:-1.2,  yaw:0.0}
  - {x:2.1,   y:1.8,  z:-1.2,  yaw:0.0}
  - {x:2.5,   y:2.2,  z:-1.2,  yaw:0.0}
  - {x:1.8,   y:2.5,  z:-1.2,  yaw:0.0}
  - {x:1.2,   y:2.5,  z:-1.2,  yaw:0.0}
  - {x:0.5,   y:2.2,  z:-1.2,  yaw:0.0}  
  - {x:0.9,   y:1.8,  z:-1.2,  yaw:0.0}
  - {x:1.5,   y:1.5,  z:-1.2,  yaw:0.0}
  - {x:2.1,   y:1.2,  z:-1.2,  yaw:0.0}
  - {x:2.5,   y:0.8,  z:-1.2,  yaw:0.0}
  - {x:1.8,   y:0.5,  z:-1.2,  yaw:0.0}  
  - {x:1.2,   y:0.5,  z:-1.2,  yaw:0.0}
  - {x:0.5,   y:0.8,  z:-1.2,  yaw:0.0}
  - {x:0.9,   y:1.2,  z:-1.2,  yaw:0.0}
  - {x:1.5,   y:1.5,  z:-1.2,  yaw:0.0}